import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import { Theme } from '@radix-ui/themes';
// import '@radix-ui/themes/styles.css';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Theme> */}
        <Navbar />
        <main className="mt-32">
          {children}
        </main>
        {/* </Theme> */}

      </body>
    </html>
  );
}
